### ISSUE TITLE
Authentication Doesn't supported by app

### ISSUE THREAD

**Issue by Diman2003** [sparckles/Robyn#1076]
### Bug Description

`
@account_apis.get("/",auth_required=True)
async def index():
    logging.info("/")

    return "Hello Diman"
`

Traceback (most recent call last):
  File "/home/developer/Desktop/SignI/app.py", line 3, in <module>
    from apis.accounts_apis import account_apis
  File "/home/developer/Desktop/SignI/apis/accounts_apis.py", line 18, in <module>
    @account_apis.get("/",auth_required=True)
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: SubRouter.get() got an unexpected keyword argument 'auth_required'

### Your operating system

None

### Your Python version (`python --version`)

None

### Your Robyn version

None

**Comment by sansyrox** [comment]
Fixed. The `TypeError: SubRouter.get() got an unexpected keyword argument 'auth_required'` is resolved — SubRouter's HTTP decorators now accept `auth_required` (and the other route flags). This was addressed by #1023 and consolidated in #1404 (merged), which removed the diverging SubRouter method overrides so they inherit the full app-level signature.

Verified on current `main`:
```python
sub = SubRouter(prefix='/account')

@sub.get('/', auth_required=True)   # no longer raises
async def index():
    return 'Hello'
```
Closing as completed — please reopen if you still hit this on the latest release.
