### ISSUE TITLE
python -m robyn --compile-rust-path "." --dev  PermissionError:

### ISSUE THREAD

**Issue by fastkits** [sparckles/Robyn#914]
### Bug Description

(py3.11) PS D:\code\sanic_demo_py11> python -m robyn --compile-rust-path "." --dev
Compiling rust file : %s .\hello_world.rs
Compiled rust file : %s .\hello_world.rs
Compiled rust files
Starting dev server...
Reloading the server
Compiling rust file : %s D:\code\sanic_demo_py11\hello_world.rs
Compiled rust file : %s D:\code\sanic_demo_py11\hello_world.rs
unknown option --compile-rust-path
usage: D:\miniconda3\envs\py3.11\python.exe [option] ... [-c cmd | -m mod | file | -] [arg] ...
Try `python -h' for more information.
Exception in thread Thread-5:
Traceback (most recent call last):
  File "D:\miniconda3\envs\py3.11\Lib\threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "D:\miniconda3\envs\py3.11\Lib\site-packages\watchdog\observers\api.py", line 205, in run
    self.dispatch_events(self.event_queue)
  File "D:\miniconda3\envs\py3.11\Lib\site-packages\watchdog\observers\api.py", line 381, in dispatch_events
    handler.dispatch(event)
  File "D:\miniconda3\envs\py3.11\Lib\site-packages\watchdog\events.py", line 272, in dispatch
    {
  File "D:\miniconda3\envs\py3.11\Lib\site-packages\robyn\reloader.py", line 143, in on_modified
    self.reload()
  File "D:\miniconda3\envs\py3.11\Lib\site-packages\robyn\reloader.py", line 108, in reload
    self.stop_server()
  File "D:\miniconda3\envs\py3.11\Lib\site-packages\robyn\reloader.py", line 105, in stop_server
    os.kill(self.process.pid, signal.SIGTERM)  # Stop the subprocess using os.kill()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [WinError 5] 

### Steps to Reproduce

 1.  
//     hello_world.rs

// rustimport:pyo3

//:
//: [dependencies]
//: rusqlite = "0.19.0"

use pyo3::prelude::*;

#[pyfunction]
fn square(n: i32) -> i32 {
    n * n * n
    // this is another comment
}
2.  python -m robyn --compile-rust-path "." --dev
3. PermissionError:

### Your operating system

Windows

### Your Python version (`python --version`)

3.11

### Your Robyn version

latest

**Comment by sansyrox** [comment]
Hey @fastkits 👋 

Are you on windows?

**Comment by fastkits** [comment]
@sansyrox  yes ， it's  on  windows 11

**Comment by asamaayako** [comment]
hey! @fastkits   I think your startup command is missing parameters. 
```
python -m robyn  appRobyn.py    --compile-rust-path "./rustdir/" --dev
```
you should You should add the startup file of Robyn application, like `appRobyn.py`

**Comment by sansyrox** [comment]
That is correct. Thank you @asamaayako 😄 

@fastkits , feel free to reopen the issue if the issue persists
